### ISSUE TITLE
Can't install from pip due to faulty package

### ISSUE THREAD

**Issue by olddesklamp** [ZebcoWeb/python-steamgriddb#2]
I've tried installing with both `pip install -U python-steamgriddb` and `pip install -U git+https://github.com/ZebcoWeb/python-steamgriddb.git` and I've had these errors spat out at me every attempt.

<details><summary>The errors in question</summary>

```
[josh@Mercury ~]$ pip install -U python-steamgriddb
Defaulting to user installation because normal site-packages is not writeable
Collecting python-steamgriddb
  Using cached python-steamgriddb-1.0.5.tar.gz (8.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9vasf0bd/python-steamgriddb_06260acea4344e9495b5720044002945/setup.py", line 7, in <module>
          setuptools.setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 475, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 258, in __init__
          getattr(self.metadata, "set_" + key)(val)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1242, in set_classifiers
          self.classifiers = _ensure_list(value, 'classifiers')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 48, in _ensure_list
          log.warning(msg)
      AttributeError: module 'distutils.log' has no attribute 'warning'. Did you mean: 'warnings'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
</details>

**Comment by ZebcoWeb** [comment]
> I've tried installing with both `pip install -U python-steamgriddb` and `pip install -U git+https://github.com/ZebcoWeb/python-steamgriddb.git` and I've had these errors spat out at me every attempt.
> 
> The errors in question

It seems this problem is solved in the latest version of **setuptools**  [#3709](https://github.com/pypa/setuptools/pull/3709)
use `pip install -U setuptools` and send the result

**Comment by olddesklamp** [comment]
That fixed it! Thanks.

**Comment by olddesklamp** [comment]
That fixed it! Thanks.

<details><summary>Output and successful installation</summary>

```
[josh@Mercury ~]$ pip install -U setuptools
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (65.6.2)
Collecting setuptools
  Downloading setuptools-65.6.3-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 74.3 kB/s eta 0:00:00
Installing collected packages: setuptools
Successfully installed setuptools-65.6.3
[josh@Mercury ~]$ pip install -U python-steamgriddb
Defaulting to user installation because normal site-packages is not writeable
Collecting python-steamgriddb
  Using cached python-steamgriddb-1.0.5.tar.gz (8.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/lib/python3.10/site-packages (from python-steamgriddb) (2.28.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests->python-steamgriddb) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.10/site-packages (from requests->python-steamgriddb) (1.26.12)
Building wheels for collected packages: python-steamgriddb
  Building wheel for python-steamgriddb (setup.py) ... done
  Created wheel for python-steamgriddb: filename=python_steamgriddb-1.0.5-py3-none-any.whl size=15223 sha256=52cf5c05c1e1bfd3d99b2541ca710241dc279144f2c5868de09a71fc5494a410
  Stored in directory: /home/josh/.cache/pip/wheels/a1/62/fb/2acb5b46043ca10d2177139d942f947b8aa7b4eb4f4575ebd8
Successfully built python-steamgriddb
Installing collected packages: python-steamgriddb
Successfully installed python-steamgriddb-1.0.5
[josh@Mercury ~]$ 
```
</details>
